### ISSUE TITLE
后台代码能提供参考下么，谢谢

### ISSUE THREAD

**Issue by MoShQing** [lazy-koala/wchat#1]

**Comment by acexy** [comment]
你好，该项目完全开源，你可以通过clone源代码或者直接在GitHub上阅读。
- html-web
    前端UI
- node-http
   前端与服务的http协议交互
- java-wekbsocket
   前端与服务的websokcet协议交互
🌹

**Comment by MoShQing** [comment]
兄台，java-websocket/src/main/java/com/thankjava/wchat/util/RedisUtil工具类类中，通过"./config/redis.properties"去读取redis的信息，但是项目中redis.properties是存放在resources目录下，代码运行到此处会报错，期待您的解答

**Comment by acexy** [comment]
该redis（包括mongodb）的连接实现可参考 [fast-toolkit](https://github.com/lazy-koala/java-toolkit) 项目。

加载配置一般分为加载项目内部resources位置和指定外部物理路径，此处加载的外部路径(相对位置)。

可以在项目下新建config文件夹，在放入相关配置。

或者使用如下代码，默认获取项目内部resources位置下redis.properties。

```java
private final static RedisManager redisManager = RedisManagerImpl.getSingleton();
```

**Comment by MoShQing** [comment]
兄台，wchat登录后，在本地存的cookie是：{token:ffd27ae1f84c01d9957fa2c46c0c5680,uid:5ce51a8325fae89e04a41aa8}，redis里查询有个key，"wchat:token:ffd27ae1f84c01d9957fa2c46c0c5680"，然后该key对应的有用户登录的信息。但是java-websocket项目中ConnectionVerifyCallBack.java类doProcess方法的传入对象ClientHandshake中包含的"Cookie" -> "uid=5ce51a8325fae89e04a41aa8; token=b1dc7b548688dee6bdeee29d2c661fdf"，此处的token值和浏览器cookie存的不一致，导致前端掉线。经过多次测试，服务器端获取的token=b1dc7b548688dee6bdeee29d2c661fdf是个固定值。请问，ConnectionVerifyCallBack.java类doProcess传入的cookie是在哪里设置的？

**Comment by acexy** [comment]
关于HTTP cookie 介绍可参考文档 [深入理解HTTP-Cookie](https://www.thankjava.com/foreend/1fae7b451e52af82bfdfef6bc7da4c25).

cookie是由浏览器根据head内容自动下发的，也就是说同域名下http(包括ws)协议的请求头都会自动下发的。

你可能需要借助浏览器的调试工具查看连接发起ws的头部信息

也许是前端妹子调试时写了一个固定的调试token字符串. @qazyuan

**Comment by qazyuan** [comment]
@MoShQing  本地启动前端项目需要手动设置cookie，你可以通过在chrome浏览器console里面使用document.cookie="key=value"来设置token，将浏览器cookie中的token设置成与服务器一直就不会掉线了
